/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Consola */

#ifndef _Included_Consola
#define _Included_Consola
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Consola
 * Method:    limpiarPantalla
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Consola_limpiarPantalla
  (JNIEnv *, jclass);

/*
 * Class:     Consola
 * Method:    colocarCursor
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Consola_colocarCursor
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     Consola
 * Method:    titulo
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Consola_titulo
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Consola
 * Method:    colorTexto
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Consola_colorTexto
  (JNIEnv *, jclass, jint);

/*
 * Class:     Consola
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Consola_stop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
